### ISSUE TITLE
tabbing and spacing

### ISSUE THREAD

**Issue by ohnx** [mandmsys/game#1]
do not use tabs. instead, use 4 spaces.

**Comment by ohnx** [comment]
also, function definitions are like
```
int main() {

}
```
and not
```
int main()
{

}
```

**Comment by mebsim** [comment]
Do I really have to do this, Can I just do it from now on

**Comment by ohnx** [comment]
ill fix the ones right niow

**Comment by mebsim** [comment]
Fine
