### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by mebsim** [mandmsys/game#1]
@ohnx what do you I should do first. Should I just upload the game I have already made, and then start changing it

**Comment by mebsim** [comment]
or do I just start from scratch? The second method will not take to much effort, but it would require a bit more time.

**Comment by mebsim** [comment]
A point in favor would be that it would be better tailored for the final result.

**Comment by ohnx** [comment]
upload your game :D

we can work on a different one later.

**Comment by mebsim** [comment]
I already uploaded my game. It is own my account.

**Comment by mebsim** [comment]
It is almost done, but does give you a good base for how to make the game.

**Comment by mebsim** [comment]
I already have started some of the planning. So no need for this.
