### ISSUE TITLE
C++ or Java

### ISSUE THREAD

**Issue by mebsim** [mandmsys/game#2]
Should I do Java or C++?

I am already familiar with Java and LWJGL and SWING, but I want to start doing these things in C++, so maybe doing this in C++ would be a good way to start.

I often learn a lot more through making basic games, then making random applications.

**Comment by ohnx** [comment]
c is the best!

**Comment by mebsim** [comment]
Are we saying C or C++

**Comment by mebsim** [comment]
I think I'm just going to go with C++
