### ISSUE TITLE
c++

### ISSUE THREAD

**Issue by ohnx** [mandmsys/game#2]
i think we should change to using c++ instead. while its harder, i think it'll be nicer for us to learn.

there are two main parts we need to do if we want to use our own game engine:
 - create the game engine
 - make the game

i think a good split would be for me to make the game engine (since i'm learning the maths and algorithms behind it) and you to make the game using the engine.

we will still have to collaborate since there will be things that will need to go into the engine that i might not think of.

this way, we interfere with each other less, too. right now, we're kind of stepping on each others' toes.

my proposal is this:
 - during the mid-terms, i will write up a little basic game engine. during this time, you can come up with a more in detailed storyline (perhaps not the guy killing random people), and maybe work more with c++.

 - after the mid-terms, we can talk about the storyline again and i'll give you some of my feedback.
after reconvening, you can start working on the actual game, and whenever you find a bug or need something added to the engine, tell me, and that way i can do so. at the same time, i will be updating the game engine, so be sure to keep pulling code.

how does this sound?

**Comment by ohnx** [comment]
fyi:
the game engine generally handles these tasks:
 - opening a window and displaying stuff on it
 - loading a level and displaying it
 - capturing when keypresses occur and moving the character accordingly
 - letting the game place objects and stuff in locations, and sending messages when the player collides with these things
(so pretty much what we've done so far)

the game focuses more on:
 - individual rooms
 - special things (ie combat scenes)
 - storyline
 - gameplay aspects/what to do when the player walks into something like a house, person
 - creating characters that you can interact with

**Comment by mebsim** [comment]
Check the plan, I have updated it, so it's not that anymore

**Comment by mebsim** [comment]
Do I have to create the entities

**Comment by mebsim** [comment]
Oh and are we going to use sprite sheets for animation, because I feel that should also be in the gameEngine

**Comment by ohnx** [comment]
so you will create a new entity like:

Entity player = new EntityPlayer();

Actually, looking at the way this is rolling out, Java might be a better choice.

**Comment by mebsim** [comment]
No I mean create the graphics, animation and things like that for the entities

**Comment by mebsim** [comment]
But if you want to change or stay is your choice, I'll work around it

**Comment by mebsim** [comment]
We are doing JAVA
